### ISSUE TITLE
error running experiment on Imagenet

### ISSUE THREAD

**Issue by thomascong121** [naver-ai/cmo#3]
Hi thanks for the great work. I try to reproduce your result on Imagenet. However, when I run your code with
`python imagenet_train.py -a resnet50 --root data/ILSVRC/ --dataset Imagenet-LT --loss_type BS \\
--data_aug CMO --epochs 100 --num_classes 1000 --workers 12 --print_freq 100  --wd 5e-4 --lr 0.02 \\
--cos --use_randaug`
It gives this error message:
`Traceback (most recent call last):
  File "imagenet_train.py", line 514, in <module>
    main()
  File "imagenet_train.py", line 69, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "imagenet_train.py", line 255, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args, weighted_train_loader=weighted_train_loader)
  File "imagenet_train.py", line 302, in train
    weighted_train_loader = iter(weighted_train_loader)
TypeError: 'NoneType' object is not iterable`
It seems like `weighted_train_loader` is set to None. However, I check the `'cifar_train.py`, the `weighted_train_loader` is a balanced dataloader. I wonder which one is correct?

**Comment by pseulki** [comment]
Hi, thank you for interest in our work!
I'm sorry for the late reply.
I noticed that there remained old codes that I missed, and I fixed the codes now!

In addition, weighted_alpha can adjust the importance of a class in a weighted_train_loader. (r in equation 2)
Thus, setting weighted_alpha = 1 is the same as a balanced loader.
The effect of setting different weighted_loader is described in Table 10.

If you have any question, please feel free to ask us :)

**Comment by thomascong121** [comment]
Thanks for the clarification.
